display:
  width: 1600
  height: 720
  resolution_ratio: 0.502
post_processing:
  color_grading:
    contrast: 2.28
    saturation: 0.84
    brightness: 1.57
    shadowsColor:
      - 0.16
      - 0.18
      - 0.3
    midColor:
      - 0.68
      - 0.518
      - 0.33
    highlightColor:
      - 0.938
      - 0.641
      - 0.438
    colorStrength: 0.47
    use: true
  eye_adaption:
    use: true
    radius: 265.644
    avgGray: 0.18
    adaptionSpeed: 0.008
    exposure: 1.0
    exposureMin: 0.942
    exposureMax: 1.283
  ssao:
    use: false
    kernelSize: 30
    radius: 0.5
    bias: 0.005
    whitePoint: 0.971
    blackPoint: 0.39
    blurSize: 2
  cavity:
    use: true
    radius: 14.0
    depthBias: 0.001
    intensity: 2.48
    blurSize: 3
    kernelSize: 23
    blackPoint: 0.26
    whitePoint: 1.0
  bloom:
    use: true
    threshold: 1.124
    levels: 4
    minRadius: 0.6
    maxRadius: 4.2
    lensDirtIntensity: 4.531
    tint:
      - 0.65
      - 0.82
      - 1.0
    intensity: 1.023
  tonemapping:
    gamma: 2.2
    tonemap: aces
  vignette:
    radius: 0.9
    softness: 0.535
    use: true
  dithering:
    use: true
    speed: 2.0
    min: 0.772
    max: 1.0
debug: true
